name: bash_scripts_admin
root: ./

on_project_start:
  - code ./
  - >
    open -na "Google Chrome"
    --args
    --new-window
    --incognito
    "https://github.com/marian13/bash_scripts_admin"

windows:
  - main:
      layout: even-vertical
      root: ./
      panes:
        - git status
  - rspec:
    layout: even-vertical
    root: ./
    panes:
      - history -s "rspec"
