version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: ${PROJECT_NAME}_app
    volumes:
      - .:/app
    tty: true
    stdin_open: true
